### ISSUE TITLE
Seperate group assignments and individual assingments

### ISSUE THREAD

**Issue by Destidom** [autograde/aguis#100]
To make it easier to distinguish the different assignments we have to make sure that a group repo for assignments and normal assignment repo is created. (like the old autograder system)

**Comment by meling** [comment]
I think the idea was to avoid keeping two separate folders for assignments, but instead indicate in the yml file the type of assignment each folder holds. The challenge is that the students probably will want to keep a separate folder locally for their individual labs and group labs and make sure to set up different remotes.

**Comment by 0xf8f8ff** [comment]
Looks to be already implemented.
