### ISSUE TITLE
Some problem with admin in group

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#101]

**Comment by meling** [comment]
Not sure if this is related, but today I was trying to edit a group as teacher (or admin??), but wasn't allowed:
```
1 errors prohibited Group from being saved:
You must be a member of the group
```

**Comment by meling** [comment]
Some more debugging. Turns out I was only given admin rights, but not weren't teacher for opsys course. But after upgrading myself to teacher (which was immediately reflected in the `ag.db`), I get this response:
```
1 errors prohibited Group from being saved:
Internal Server Error
```

**Comment by Destidom** [comment]
I have not been able to reproduce that last error.
Steps I'v tried to use to reproduce it.
1. Sign in as admin
2. Enroll to a course
3. Promote my self to teacher.
No Internal server error.
