### ISSUE TITLE
Frontend: User feedback during course creation

### ISSUE THREAD

**Issue by meling** [autograde/aguis#104]
While creating a new course there are two issues with the frontend:

1. Selecting an organization provides little feedback to the user (not possible to see that a specific organization has been selected).
2. When pressing `Create course` button, it should show a progress indicator or some way to indicate that the button press was registered; for example, we could display the text `Creating course repositories...` or something like that. Currently, it can take a while before the course was created (it needs to talk with GitHub to create repos etc), and this could leave the user thinking that the button press was not recorded.

**Comment by 0xf8f8ff** [comment]
Selected organization is now clearly highlighted, `Create course` button displays relevant message during course creation/update
