### ISSUE TITLE
Group Creation fails when group name is a user name

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#110]
If a user creates a group with the same name as the user's username at github, it will fail to create a new team for that group, and the repo is not assigned correctly

**Comment by meling** [comment]
So, this should impact several of the groups already created for DAT520. This sounds like an easy fix, to simply deny such group names that overlap with any of the group member's names. Or would we have to check against all usernames in the whole org?

**Comment by 0xf8f8ff** [comment]
Not anymore
