### ISSUE TITLE
Spec: Repository structure for a course

### ISSUE THREAD

**Issue by meling** [autograde/aguis#17]
The new autograder will assume the following repository structure. These will be created automatically when a course is created.

Repository name | Description | Access 
----------------|-------------|--------
`course-info`   | Holds information about the course. | Public
`assignments`   | Contains a separate folder for each assignment. | Students, Teachers, Autograder
`username`      | Created for each user `username` in autograder | Student, Teachers, Autograder
`tests`         | Contains a separate folder for each assignment with tests for that assignment. | Teachers, Autograder
`solutions`     | Typically contains assignments, tests, and solutions that pass the tests. | Teachers

*PS: These repository names should be defined as variables in the frontend and backend, as appropriate, so that they can be changed for the different courses rather than being hardcoded into the code at various places. Other names that people may use include: templates, labs, homework, exercises etc.*

*PPS: In autograder, Teacher means any teaching staff, including teaching assistants and professors alike.*

The `assignments` folder has a separate folder for each assignment. The short name for each assignment can be provided in the folder name, for example `single-paxos` or `state-machine-replication`. Typically, the deadline gleaned from the `ag.yml` file will determine the ordering of the assignments as they appear in lists in the frontend. We may provide an alternative way to order the assignments. Some courses may simply use short names, such as `lab1`, `lab2`, and so on. These will be sorted by the frontend as expected.

The `username` is actually the github or gitlab user name. This repository will initially be empty, and the student will need to set up a remote label called `assignments` pointing to the `assignments` repository, and pull from it to get any template code provided by the teaching staff. 

The `tests` folder is used by autograder to run the tests for each of the assignments. The folder structure inside `tests` must correspond to the structure in the `assignments` repo. Each assignment folder in the `tests` repository contains one or more test file and a `ag.yml` configuration file that will be picked up by autograder test runner. The format of this file will be specified elsewhere, but it will describe various aspects of an assignment, such as submission deadline, approve: manual or automatic, programming language, test commands, etc.

The `solutions` folder should never be shared with anyone except teachers. This folder is not used by autograder, but is created as a placeholder for the teaching staff to prepare and test the assignments locally. This folder will typically be used as the source for creating the `assignments` folder and `tests` folder.

Currently, teaching staff needs to populate these repositories manually for the course. This is important so as to prevent revealing commit history from old instances. That is, these repositories should not be cloned or forked from an old version of the course. 

We currently have not specified a separate repository for group assignments, as we hope to find a way to avoid a separate group repository. Once this has been decided, we will update this spec.

**Comment by 0xf8f8ff** [comment]
Moved to documentation.
