### ISSUE TITLE
Listening to push on master branch

### ISSUE THREAD

**Issue by vinaysetty** [autograde/aguis#183]
It seems like ag currently triggers a build whenever there is a push to any branch in the GitHub repository of the students like username-labs. Ideally it should only run builds when there is a push to the master branch. We can then make sure that students can work on a different branch and once their submission is ready they can merge with the master branch. This is to avoid expensive builds (especially for machine learning related tasks) after each push.

**Comment by meling** [comment]
There is a fix for this in the master branch now. However, we should document this feature somewhere. Where does it make sense to put such info @vinaysetty @0xf8f8ff ?

**Comment by 0xf8f8ff** [comment]
Autograder's Help page seems like a reasonable place. But should probably also be mentioned in the readme file for teachers.

**Comment by meling** [comment]
As mentioned above, this has been fixed for a while now, but only now has it been documented in [doc/submission-template.md](https://github.com/autograde/aguis/blob/master/doc/submission-template.md). Teaching staff may use this template to document the submission process in their own courses. Hence, closing this issue.
