### ISSUE TITLE
Assignments from git repository

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#19]
Autograder should clone the `tests` repository to disk, and recursively scan the folder structure and extract the `ag.yml` files with information about the assignments. This information should be stored in the database, so that it is available to be requested from the frontend. 

The frontend should use `/courses/:id/assignments` to request information about all assignments. See issue #2 for details on the endpoint path.

Response format for one assignment:

```JSON
{
    "id": 1,
    "courseid": 1,
    "name": "Lab 1",
    "deadline": "2018-04-23T18:25:43.511Z",
    "approve": "manual | automatic",
    "programminglanguage": "Go",
}
```
(more information may be added to this format later.)

Currently: Make the frontend talk to the backend and basic database functions plus basic model.

**Comment by meling** [comment]
Progress on this: YML, DB and endpoint should work. Missing tasks:
- Cloning the repo.
- Webhooks? @s111 
- Need button in the frontend as well (in case webhooks fails)

**Comment by nicro950** [comment]
Everything is done except webhooks

**Comment by nicro950** [comment]
#79
