### ISSUE TITLE
Backend API

### ISSUE THREAD

**Issue by s111** [autograde/aguis#2]
Opening this issue for tracking the status and discussion around the backend API.

- [x] `/logout` (#5)
  - [x] **GET**: Logs the user out and redirects to `/`.
  - [x] *Query*: redirect=**url**.
    - [x] Change redirect to **url**.
- [x] `/auth/:provider` (#5)
  - [x] `/callback`
         The provider will redirect to this URL after authentication.
    - [x] **GET**: Finish authentication, write cookie to client and redirects to `/`.
    - [x] *Query*: redirect=**url**.
      - [x] Change redirect to **url**.
- [ ] `/api/v1`
   Accessing `/api/v1` requires authentication through `/auth/:provider`.
  - [x] `/directories`
    - [x] **POST** (#9): List provider directories which the user is a member of.
  - [ ] `/courses`
    - [ ] **POST**: Create new course.
      - [x] Add entry in database.
    - [ ]  **GET**: List courses
      - [x] List entries in database.
    - [ ] `/:id`
      - [ ] **GET**: List course
      - [ ] **PUT**: Update course
    - [ ] `/:id/assignments`
      - [ ] **GET**: List assignments for course
    - [ ] `/:id/assignments/:aid`
      - [ ] **GET**: List assignment `aid` for course
      - [ ] **PUT**: Update assignment `aid` for course

**Comment by meling** [comment]
1. Suggest to keep the description of each api call separate for `/(github|gitlab)/organizations` and `courses`.
2. Suggest to make separate entry for **GET** and **POST** `/courses`.
3. Suggest moving the last sentence "Accessing `/api/v1` to the item `/api/v1`, either in parens or on a new line.
4. The **POST** to `/courses` seems a bit odd. Maybe this deserves a separate api call, e.g. `/new/course/{orgid}` or `/newcourse/{orgid}`. I can imagine that we will also have `/new/student` and `/new/group` or something like that. (I don't know what is common practice wrt. REST api naming)

**Comment by s111** [comment]
I've update the first post.
I will try to create separate issues and link to them when I start the implementation of individual endpoints.
Using **GET**/**POST** on `/courses` is, I think, the REST way of doing it.

- **GET** `/things`: Lists the things resource (e.g., returns an array of things).
- **POST** `/things`: Adds something to the collection of things (e.g., append to the end of an array).
- **GET** `/things/:id`: List an individual thing (e.g., accessing an element of an array).
- **PUT** `/things/:id`: Update an individual thing (e.g., updating an element of an array).

**Comment by 0xf8f8ff** [comment]
All described functionality seems to have already been implemented.
