### ISSUE TITLE
Endpoint for getting/updating a course

### ISSUE THREAD

**Issue by joenayjoe** [autograde/aguis#20]
**GET** _/courses/:id_      get a course by id
return a JSON object if found by id
```
{ 
  "id": 16,
  "name": "asd",
  "code": "asd",
  "year": 2222,
  "tag": "Spring",
  "provider": "github",
  "directoryid": 23650610
}
```

**PUT** _/courses/:id_      updates an existing course
Expected JSON payload:
```
{
    "name": "C++",
    "code": "DAT100",
    "year": 2017,
    "tag": "Spring",
    "provider": "github",
    "directoryid": 23650610
  }
```
Endpoint returns status code 200 if updated

**Comment by sebastianmpedersen** [comment]
I think the PUT request should just return no content 200. In addition, as you are updating the whole database row, you need to ensure that the frontend actually sends all the required data fields, or some columns will end up being emptied.

**Comment by s111** [comment]
I think the PUT request should just return no content 200. In addition, as you are updating the whole database row, you need to ensure that the frontend actually sends all the required data fields, or some columns will end up being emptied.

**Comment by joenayjoe** [comment]
Ok I will make the changes. For validation, I am using valid() function you wrote to validate new course. So if frontent does not send all required fields, validation will fail and hence will not update the row.
