### ISSUE TITLE
Enroll a user to a course

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#21]
Create an endpoint for enrolling a student to a course

`POST /enrolluser`

```JSON
{
    "userid": 1,
    "courseid": 1
}
```

UPDATE: 

`PUT /courses/:id/users/:userid`

**Comment by s111** [comment]
I think @meling is working on this, and the endpoint will not be named `/enrolluser`. I'll try to write up how this is supposed to work, tomorrow.

**Comment by s111** [comment]
See #22.
