### ISSUE TITLE
Clean up handleSearch and handleOnchange methods

### ISSUE THREAD

**Issue by meling** [autograde/aguis#255]
There are many uses of various search functions with similar, but slightly different code for finding users, groups, courses etc in the codebase. These are typically named either `handleOnchange()` or `handleSearch()`. Some issues with these functions is that they are inconsistent in the use of method vs field, e.g.: `user.email.toLowerCase()` vs `usr.getEmail().toLowerCase()` and other problems. Needless to say, I think we should move the boolean expression of these functions to a set of global functions that takes a `User`, `Group` or `Course` object as input, e.g.:

```typescript
import { User, Group, Course } from '../proto/ag_pb';

export function search(query: string, t: User | Group | Course, predicate: boolean = true): boolean {
    if (t instanceof User) {
        return findUser(query, t, predicate);
    } else if (t instanceof Group) {
        return findGroup(query, t, predicate);
    } else if (t instanceof Course) {
        return findCourse(query, t, predicate);
    }
    return false;
}

function findUser(query: string, user: User, predicate: boolean = true): boolean {
    if (!user) {
        return false;
    }
    return predicate
        && user.getName().toLowerCase().indexOf(query) !== -1
        || user.getEmail().toLowerCase().indexOf(query) !== -1
        || user.getLogin().toLowerCase().indexOf(query) !== -1
        || user.getStudentid().toLowerCase().indexOf(query) !== -1;
}

function findGroup(query: string, grp: Group, predicate: boolean = true): boolean {
    if (!grp) {
        return false;
    }
...
```

Note that the `predicate` can be used to represent more involved expressions, such as `this.state.selectedStudents.indexOf(student) === -1`.

I added these to `helper.ts` to try things out (there may be better places for them...), but haven't committed them, since I don't want to clutter other pending changes, and these should be committed together with changes to the corresponding `handleSearch()` and `handleOnchange()` methods. (At the same time, we should probably harmonize the naming of these two methods.)

**Comment by meling** [comment]
In the `handleSearch()` and `handleOnchange()` methods, we should consider replacing `forEach` loops with `map` and `filter` functions instead.

See https://medium.com/poka-techblog/simplify-your-javascript-use-map-reduce-and-filter-bd02c593cc2d

**Comment by 0xf8f8ff** [comment]
All done.
