### ISSUE TITLE
Update frontend due to API change

### ISSUE THREAD

**Issue by s111** [autograde/aguis#26]
As we have stopped using ?user=x and ?course=x, some XHR's on the frontend is broken, these need to be updated. The frontend also requests courses?user=0 which is incorrect.

**Comment by nicro950** [comment]
I have fixed the one that requests user=0. Else it is only the echo.NotFoundHandler, I am missing in the frontend.

**Comment by s111** [comment]
[ServerProvider.ts#L34](https://github.com/autograde/aguis/blob/5965c476bdd729b9a2c3187d918a651a941084c7/public/src/managers/ServerProvider.ts#L34)
[ServerProvider.ts#L45](https://github.com/autograde/aguis/blob/5965c476bdd729b9a2c3187d918a651a941084c7/public/src/managers/ServerProvider.ts#L45)

**Comment by nicro950** [comment]
You were a little to early with that, they are up now

**Comment by s111** [comment]
👍
