### ISSUE TITLE
Fix spacing between github avatars for selecting organization for course

### ISSUE THREAD

**Issue by meling** [autograde/aguis#31]
Frontend issue. When more than two rows are needed, it doesn't look nice.

**Comment by joenayjoe** [comment]
Fixed and tested with dummy data as I do not have many organizations in github.

**Comment by meling** [comment]
Still looks the same. Maybe we can postpone fixing this until I'm there so we can do it in my view.

<img width="835" alt="screenshot 2017-07-21 12 05 10" src="https://user-images.githubusercontent.com/810999/28459262-085a0200-6e0d-11e7-9149-349691e3e13a.png">

**Comment by joenayjoe** [comment]
This is how it looks in my screen. :) 
![screenshot from 2017-07-21 12-39-18](https://user-images.githubusercontent.com/4953463/28460352-ed082946-6e11-11e7-83d2-a8d2c8e7eeb1.png)

**Comment by joenayjoe** [comment]
May be i need to check with different browser. I tested on firefox.

**Comment by meling** [comment]
I just checked now and it looks better now. But it still needs some tweaking since some organization names may be a bit long:

<img width="828" alt="screenshot 2017-07-26 10 30 04" src="https://user-images.githubusercontent.com/810999/28611882-9b2fce78-71ed-11e7-8e5f-ac3df41903f5.png">

(I'm reopening to ensure that it gets seen.)

**Comment by s111** [comment]
I get the same problem in Firefox due to long organization names.

**Comment by joenayjoe** [comment]
Fixed long organization names issue. I tested on both Firefox and Chrome and it seems working from my end.

**Comment by meling** [comment]
Names are being cut off. I guess it is one solution. 

<img width="753" alt="screenshot 2017-07-27 12 12 10" src="https://user-images.githubusercontent.com/810999/28665716-eab48b14-72c4-11e7-86a1-ae6791211c2c.png">

**Comment by joenayjoe** [comment]
Yes name are being cut off if overflow and tooltip is being added. Hover over an organization will show the full name of the organization.

**Comment by s111** [comment]
Maybe you could use:
```css
text-overflow: ellipsis;
```
Names will then be, e.g., `uis-dat320...` as opposed to `uis-dat320-fa` (where the a is actually cut off)

**Comment by meling** [comment]
I think this works fine now. Can it be closed @joenayjoe ?

**Comment by joenayjoe** [comment]
Ok I am closing the issue.
