### ISSUE TITLE
Have the scm tool extract access tokens from the database

### ISSUE THREAD

**Issue by s111** [autograde/aguis#37]
The `scm` tool should be able to take an autograder database file and an id corresponding to a `remote_identities` table row. The access token can thus be retrivied from the database, and the access token argument isn't needed.

**Comment by meling** [comment]
@s111 I believe this is solved by commit d5a7434487e0440cc03b8ba14fedd31c9c78a4f0. I forgot to make it a PR, but feel free to check my code and close this if it is ok.
