### ISSUE TITLE
When user's registration info incomplete; show profile update page only

### ISSUE THREAD

**Issue by meling** [autograde/aguis#39]

**Comment by meling** [comment]
Is this issue receiving any love?

**Comment by nicro950** [comment]
Now it is, which fields should be added to the user object? 
Name,
StudentNR
Studentemail ?

**Comment by meling** [comment]
Yes. I think those are the ones we need for now at least.

**Comment by meling** [comment]
This page should fetch user details from the server, since this information is already collected when authenticated with a git provider such as github. This should provide information for first name, last name and email. Thus, most of the time, a user only needs to fill the student/employee number.

**Comment by nicro950** [comment]
@meling Should we just close this issue, and open a new one regarding filling in information automatically?

**Comment by meling** [comment]
SGMT. Please open new issue. I think there is already server-side support for fill the profile data.
