### ISSUE TITLE
Create new ID types instead of using uint64

### ISSUE THREAD

**Issue by meling** [autograde/aguis#43]
To make IDs easier to distinguish, we should use
```go
type UserID uint64
type CourseID uint64
type GroupID uint64
```
and so on as needed.

This will require touching lots of files, so should be done in coordination with others to avoid merge conflicts.

**Comment by meling** [comment]
Should the `json:"id"` fields be changed accordingly to e.g. `json:"userid"`?

PS: Note that some places we use field name/variable name the same as the new ID type, e.g. in `RemoteIdentity` struct the `UserID` field would be indistinguishable from the type. But I think that is ok.

**Comment by 0xf8f8ff** [comment]
Now that we have distinct request types, all IDs have specific names and are strongly typed.
