### ISSUE TITLE
Set up admin automatically

### ISSUE THREAD

**Issue by meling** [autograde/aguis#49]
I always forget to run the `agctl` command to set up the admin user. I would like to make that happen automatically when starting the server for the first time with an empty database. Are there any concerns with doing this s111?

**Comment by s111** [comment]
I think using agctl or just flipping the bool using sqlite3 is the best option. We could have the first user to register always be an admin. The only concern I have is the added complexity.

**Comment by meling** [comment]
All teachers will be admin in the sense that they can create courses etc. The first user to be admin will be responsible for promoting other teachers (at least the first other teacher) to admin role. So `User.ID=1` has no special meaning except always being admin. So in `CreateUserFromRemoteIdentity` we can simply set `IsAdmin:=true` for the first user. This does not add much complexity IMO. Am I missing something @s111?

**Comment by s111** [comment]
No I don't think so, that's why I suggested having the first user always be an admin, as it's the least intrusive change.

**Comment by meling** [comment]
@s111 please review my commit 6caf767 ; can we close this issue?

**Comment by s111** [comment]
LGTM
