### ISSUE TITLE
Frontend design issues

### ISSUE THREAD

**Issue by meling** [autograde/aguis#53]
- [x] I would like to have an appealing first page with some graphics and stuff. We can copy some of the text and graphics from the old Autograder. 

- [x] I like the top menu bar in black as is, because it looks similar to github's menu bar. I guess we could use bold faced fonts. 

- [x] But perhaps the most important issue for me is that I don't want a dropdown menu for the Login. Instead it would be much better to do something like is done here, where they have more Sign up alternatives on the actual page as large buttons: https://buddy.works

The top menu bar should only hold have the text `Sign in with ` followed by the supported providers's icons, similar to the approach used in the old Autograder.

Please don't use the terms Login and Logout.

- [x] When signed in, we should have + symbol to access a dropdown menu on the right like Github does for 
- [x] New Course (only for administrators)
- [x] Join Course (for all)
- [x] (and possibly other things that needs to be created)

- [x] We should also show the user name OR avatar with a dropdown menu to access the user's profile and sign out, also like Github does it. This menu should also have a Help menu item, instead of having the help page on the top menu bar.

**Comment by nicro950** [comment]
If you move the help page, how are you going to access it when you are not logged in? And you want the sign in like this ?

![image](https://user-images.githubusercontent.com/1964338/28895926-a1b83030-77da-11e7-971a-55b7a7be7d66.png)

**Comment by joenayjoe** [comment]
Front end now look like this:

Before sign in: 
![screenshot from 2017-08-07 14-32-09](https://user-images.githubusercontent.com/4953463/29028777-9ab193b8-7b85-11e7-916f-98a3766f2a9a.png)

After Sign in:
![screenshot from 2017-08-07 15-28-57](https://user-images.githubusercontent.com/4953463/29028787-9e4ab8ec-7b85-11e7-9db5-de96a1edb516.png)

**Comment by meling** [comment]
Looks good
