### ISSUE TITLE
Need links to navigate from frontend to github repositories

### ISSUE THREAD

**Issue by meling** [autograde/aguis#55]
There must be shorthand links to get to the following pages on github:

* For students: `course-info` and `assignments` and the `student_name` repo
* For teachers (in addition to the above): `solutions` and `tests`

(see the old autograder for some inspiration) 

The left side menu bar should be more similar to the old autograder.

**Comment by nicro950** [comment]
Why is this marked as a bug? It is not something does not work, but it is something that does not exist yet, missing the endpoint at the server side to be able to request that kind of information.

**Comment by nicro950** [comment]
A couple of things on this one. If we are going to show the links, how do we know which link is the correct one? We could just hard code the string for the repository so assignments, would always be assignments, but that would prevent a teacher from changing it. Else we need a way to tell what kind of repositories it is or have a separate table which contains the actual links for the user repository.

**Comment by meling** [comment]
You can get that information from the server through an endpoint that gives you the list of names for the repos. (this endpoint does not exist yet, but it should.)

**Comment by nicro950** [comment]
Yes, but how do you know what the different names map to? For instance, if I choose to call assignments repo for test, and test repo for assignments, where do I get that information from which says that test is the assignment repo, and assignment is the test repo? 

Or should we not allow to have other names of the repositories in the future?

**Comment by meling** [comment]
For now we will create a map in the frontend ServerProvider with hardcoded repo names. Later we can add an endpoint to the server to fetch `/reponames` from the server.
