### ISSUE TITLE
Update PatchUser function in backend

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#57]
Update the PatchUser to support updating more fields in the user object, then just the IsAdmin field. Frontend needs this feature to be able to update the user information for the user profile page.

**Comment by meling** [comment]
I briefly looked into this. I wonder if the initial call to `CreateUserFromRemoteIdentity` could include user information?

**Comment by meling** [comment]
Just found out that it does already get user information from the git provider during the auth process.

**Comment by meling** [comment]
This has been implemented in commit abd7137ba6dd. @nicro950 please try it now from the frontend.

**Comment by joenayjoe** [comment]
Github and Gitlab does not provide FirstName and LastName as separate fields though they provide Name field which contains full name. So we need to split Name field from the provider api response. If full name is a two words name, splitting is straight forward. But if the name has three or more words, how should we split the name? 
example:
_two words name:_
```
full name: Junaid Alam

first name: Junaid
last name: Alam
```

_three words name_
```
full name: Petter John White

first name: Petter
last name: John White 
OR
first name: Petter John
last name: White
```
@meling

**Comment by meling** [comment]
Actually, I don't think we need to separate the name in autograder either. We can just use one `FullName` field.

**Comment by joenayjoe** [comment]
Ok then we need to update User model accordingly.

**Comment by meling** [comment]
I'll fix it.

**Comment by meling** [comment]
Fixed by commit f361d27.

**Comment by meling** [comment]
@nicro950 @joenayjoe does this work now from the frontend, or do we need something more from the backend? If not, I think we can close this issue.

**Comment by joenayjoe** [comment]
Closing the issue as it seems the fix works fine for now.
