### ISSUE TITLE
Create new course page need not show radio button

### ISSUE THREAD

**Issue by meling** [autograde/aguis#58]
When an Autograder is deployed with a single provider (which is a likely scenario), we need not show a radio button to select a provider. Instead we should just show a list of github organizations (when provider is github that is). The provider radio button should be hidden, when there is only one provider.

**Comment by meling** [comment]
@nicro950 I've tried to implement this, but it seems to cause an infinite loop and I have no idea why; see commit d441cef. I doing this to collect organizations when there is only one provider:
```typescript
this.getOrganizations2(this.props.providers[0], this.updateOrganisationDivs);
return <div />;
```
(tried to reuse getOrganizations() but couldn't refactor it to take a provider string; not sure why?)

**Comment by nicro950** [comment]
Fixed and refactored
