### ISSUE TITLE
When a user enrollment to a course is accepted we should create a user repo

### ISSUE THREAD

**Issue by meling** [autograde/aguis#60]
If the teacher accepts a student enrollment, a user repo should be created. Access to this repo should only be given to teachers and the student.

@s111 is it intentional that `SetEnrollment` is called multiple times for the same user/course combination? I mean `db.CreateEnrollment` seems to be called for both the initial course sign up by the user and later by the teacher changing the enrollment status to `AcceptEnrollment` or `RejectEnrollment`.

**Comment by meling** [comment]
I made a test case for `web.SetEnrollment()`, and it seems to work. But note that `GetEnrollmentByCourseAndUser()` does not populate the `*Course` and `*User` pointers in the `Enrollment` struct. Maybe they should be filled or removed from the struct??

**Comment by s111** [comment]
I don't think I created the `GetEnrollmentByCourseAndUser` method, however looking at it, the `*Course` and `*User` doesn't need to be set, as it looks like we actually only interested in the enrollment status. I think we should leave the fields in the struct as it shows the relation (in addition to `CourseID` and `UserID`), and we might want to populate them (maybe we already do) in some other method.

`CreateEnrollment` is called for the teacher, when a teacher creates a new course, i.e., what we did in #38. In addition, `CreateEnrollment` is also called when a user joins a course, i.e., an enrollment entry is created in the database with status = pending, this is later changed by the teacher calling `AcceptEnrollment` or `RejectEnrollment`. It does look to me like the (web) `SetEnrollment` implementation needs to be look at one more time though. It always creates a new enrollment, which I think is wrong, it shouldn't create a new enrollment if we want to accept/reject an existing enrollment...

**Comment by meling** [comment]
I agree that it should create a new enrollment for each call to `SetEnrollment`. Perhaps @nicro950 could confirm this.

**Comment by joenayjoe** [comment]
I think I created `GetEnrollmentByCourseAndUser` method to get a record of an Enrollment specified by courseID and userID. 
web.GetGroupByUserAndCourse() and web.NewGroup() are using that method. I didn't populate *Course and *User because we are interested in status and groupID fields only.

**Comment by meling** [comment]
But we shouldn't call `CreateEnrollment` multiple times for the same combination of `courseID` and `userID`. Instead we need to ask the db if there is already an enrollment that we need to update.

**Comment by s111** [comment]
Currently we have:
```go
courses.PUT("/:cid/users/:uid", web.SetEnrollment(db))
```
This should only create a new enrollment with status = pending, i.e., the payload should not contain a status field.
In addition, we should create:
```go
courses.PATCH("/:cid/users/:uid", web.UpdateEnrollment(db))
```
Which can accept/reject an existing enrollment, i.e., the payload should have the status field.

**Comment by meling** [comment]
Ok, I can implement `web.UpdateEnrollment(db)`.

**Comment by nicro950** [comment]
Right now the CreateEnrollment function creates a new enrollment if it does not exist, or updates a one if it exists, so that is the reason only that one is used right now,

**Comment by s111** [comment]
I think `CreateEnrollment` needs to be changed to fail if an enrollment already exists. It's currently possible to call `CreateEnrollment` then `AcceptEnrollment`, then `CreateEnrollment` again, creating a duplicate enrollment for the same course/user combination. This is possible because the old enrollment has changed status to `Accepted` no longer matching the `Pending` status that `CreateEnrollment` looks for when doing the `FirstOrCreate` call.
