### ISSUE TITLE
Show serverside errors if new course creation fails.

### ISSUE THREAD

**Issue by joenayjoe** [autograde/aguis#67]
- should show server side errors to end user if course creation fails.

**Comment by joenayjoe** [comment]
Fixed by commit [25faa37](https://github.com/autograde/aguis/commit/af09717b3c4f0b60b77d8d73b4df50fb9bb8bcda)

@meling ,   @s111 , server returns `500: Internal Server Error `if repository creation fails. I think it would be better to return a more informative error message so that end user can understand.

**Comment by meling** [comment]
This needs to be fixed. It needs some changes to the `web.NewCourse()` function.

**Comment by meling** [comment]
The issue that currently causes this is that we don't detect existing webhooks. Here is some log output.
```
INFO[0065] Failed to create webhook for repository       error="POST https://api.github.com/repos/autograder-test/course-info/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:Hook already exists on this repository}]" repo=course-info
ERRO[0065] POST https://api.github.com/repos/autograder-test/course-info/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:Hook already exists on this repository}]
```
Should we query github/gitlab for existing webhooks in the repos or check for a specific error message, such as `Hook already exists on this repository`?

**Comment by s111** [comment]
I have this TODO in the code.
```go
			// TODO: Make sure CreateHook doesn't return an error if
			// the call fails due to an already existing identical
			// hook.
```

However, I think maybe we should, on any error (for now at least) just give the user a button to press which delete the current repository and creates a new one.

**Comment by meling** [comment]
@s111 I saw the TODO, but I guess the question is how to check for this particular error.

**Comment by meling** [comment]
About providing a button to delete and create a new one. This complicates things a bit. Should it be per repository we are trying to create, or for all repos. Should it be a button to Reset (github) organization, removing teams and other repos as well or something else?

**Comment by s111** [comment]
Thinking about it a bit more a `Reset organization/group` button makes more sense, as then we don't have to store any intermediate state information.

**Comment by 0xf8f8ff** [comment]
Most server-side errors will return a descriptive error message.
