### ISSUE TITLE
Gitlab provider does not have enough scope to list groups

### ISSUE THREAD

**Issue by nicro950** [autograde/aguis#68]
It looks like it is currently not possible to list Gitlab groups in the frontend because the backend is complaining about `{error: insufficient_scope}, {error_description: The request requires higher privileges than provided by the access token.}`

**Comment by s111** [comment]
It looks like this is still working correctly, you need to remember to authenticate against /auth/{provider}-teacher to gain the "teacher" scope. The default is to request the lowest possible scope, i.e., students shouldn't have to give Autograder access to read/write repositories. If this is not right, please re-open the issue.
