### ISSUE TITLE
Course configuration needs attribute for passing level

### ISSUE THREAD

**Issue by meling** [autograde/aguis#7]
The course configuration panel needs to have some way to specify the passing level for each assignment, e.g. 85%. Maybe all assignments should have the same passing level? Do we need to distinguish this per assignment?

**Comment by nicro950** [comment]
I have not experienced any situation where there is different passing level between assignments in a single course, so personally, I think it is suffisient with a passing level specific to a course. Another question related to passing levels is, should it be possible to have graded assignments or just passed/failed assignments

**Comment by meling** [comment]
Agree that we only need one attribute per course. Yes, we should have both pass/fail and support for graded assignments. So far we have really only used the score as a pass/fail thing, but I can imagine using it for grading as well, for example if we use it for "controlled" exams.

**Comment by meling** [comment]
This will be replaced by other configuration of grading schemes.
