### ISSUE TITLE
Utils.go: Why is n==0 important here?

### ISSUE THREAD

**Issue by Destidom** [autograde/aguis#95]
Why do we return an error if `n==0`? I think this should be documented or maybe rename the function, since right now there is no explenation as of why we return an error for `n==0`.

https://github.com/autograde/aguis/blob/c7415011c67437ca394468d5c9d6dccd4145b1f9/web/util.go#L22-L30

**Comment by meling** [comment]
Agree this should be documented or renamed to e.g. `parseID()`. It is only used in the `web` package for parsing various ID types needed by the database. That is, I think the database didn't like it if the ID was 0.

**Comment by meling** [comment]
Closed by 8e2579f94cf08de32471dc78a6f7b87c3bd44ff4
